
# ZH-CN
# Names
CombineSoldierSubtitle_Name.Leader=队长
CombineSoldierSubtitle_Name.Flash=闪电
CombineSoldierSubtitle_Name.Ranger=骑兵
CombineSoldierSubtitle_Name.Hunter=猎人
CombineSoldierSubtitle_Name.Blade=刀锋
CombineSoldierSubtitle_Name.Scar=刀疤
CombineSoldierSubtitle_Name.Hammer=击锤
CombineSoldierSubtitle_Name.Sweeper=清道夫
CombineSoldierSubtitle_Name.Swift=激流
CombineSoldierSubtitle_Name.Fist=铁拳
CombineSoldierSubtitle_Name.Sword=刺刀
CombineSoldierSubtitle_Name.Savage=野人
CombineSoldierSubtitle_Name.Slash=切口
CombineSoldierSubtitle_Name.Razor=剃刀
CombineSoldierSubtitle_Name.Stab=尖刺
CombineSoldierSubtitle_Name.Spear=渔叉
CombineSoldierSubtitle_Name.Striker=前锋
CombineSoldierSubtitle_Name.Dagger=匕首

CombineSoldierSubtitle_Name.Ghost=幽灵
CombineSoldierSubtitle_Name.Reaper=死神
CombineSoldierSubtitle_Name.Nomad=游魂
CombineSoldierSubtitle_Name.Hurricane=飓风
CombineSoldierSubtitle_Name.Phantom=幻影
CombineSoldierSubtitle_Name.Judge=法官
CombineSoldierSubtitle_Name.Shadow=暗影
CombineSoldierSubtitle_Name.Slam=猛击
CombineSoldierSubtitle_Name.Stinger=毒刺
CombineSoldierSubtitle_Name.Storm=风暴
CombineSoldierSubtitle_Name.Vamp=吸血鬼
CombineSoldierSubtitle_Name.Winder=卷线
CombineSoldierSubtitle_Name.Star=海星

CombineSoldierSubtitle_Name.Freeman3=弗里曼
CombineSoldierSubtitle_Name.AntiCitizenOne=反叛者一号
CombineSoldierSubtitle_Name.TargetOne=目标一
CombineSoldierSubtitle_Name.Priority1Objective=一级通缉目标
CombineSoldierSubtitle_Name.Ghost2=幽灵-2

CombineSoldierSubtitle_Name.Apex=Apex
CombineSoldierSubtitle_Name.Ion=离子
CombineSoldierSubtitle_Name.Jet=Jet
CombineSoldierSubtitle_Name.Kilo=Kilo
CombineSoldierSubtitle_Name.Mace=Mace
CombineSoldierSubtitle_Name.Nova=Nova
CombineSoldierSubtitle_Name.Payback=Payback
CombineSoldierSubtitle_Name.Sundown=落日
CombineSoldierSubtitle_Name.Uniform=Uniform
CombineSoldierSubtitle_Name.Boomer=Boomer
CombineSoldierSubtitle_Name.Echo=回声
CombineSoldierSubtitle_Name.Flatline=Flatline
CombineSoldierSubtitle_Name.Helix=Helix
CombineSoldierSubtitle_Name.Ice=Ice
CombineSoldierSubtitle_Name.Quicksand=流沙
CombineSoldierSubtitle_Name.Ripcord=Ripcord
