
# ZH-CN
# Names
MetropoliceSubtitle_Name.Defender=防卫队
MetropoliceSubtitle_Name.Hero=英雄
MetropoliceSubtitle_Name.Jury=陪审团
MetropoliceSubtitle_Name.King=国王
MetropoliceSubtitle_Name.Line=线条
MetropoliceSubtitle_Name.Patrol=巡逻队
MetropoliceSubtitle_Name.Quick=疾风
MetropoliceSubtitle_Name.Roller=卫兵
MetropoliceSubtitle_Name.Stick=铜锤
MetropoliceSubtitle_Name.Tap=闪击
MetropoliceSubtitle_Name.Union=联盟
MetropoliceSubtitle_Name.Victor=常胜
MetropoliceSubtitle_Name.Xray=射线
MetropoliceSubtitle_Name.Yellow=黄色
MetropoliceSubtitle_Name.Vice=虎钳

# Maps
MetropoliceSubtitle_Map.Block=街区
MetropoliceSubtitle_Map.Zone=区域
MetropoliceSubtitle_Map.Sector=区域

MetropoliceSubtitle_Map.StationBlock=车站区
MetropoliceSubtitle_Map.TransitBlock=运输区
MetropoliceSubtitle_Map.WorkforceIntake=职业分配中心

MetropoliceSubtitle_Map.CanalBlock=运河区
MetropoliceSubtitle_Map.StormSystem=风暴系统
MetropoliceSubtitle_Map.WasteRiver=废水河
MetropoliceSubtitle_Map.DeservicedArea=限制区

MetropoliceSubtitle_Map.IndustrialZone=工业区
MetropoliceSubtitle_Map.RestrictedBlock=限制区
MetropoliceSubtitle_Map.RepurposedArea=再生区

MetropoliceSubtitle_Map.CondemnedZone=禁运区
MetropoliceSubtitle_Map.InfestedZone=感染区
MetropoliceSubtitle_Map.NonPatrolRegion=非巡逻区

MetropoliceSubtitle_Map.ExternalJurisDiction=外部管辖区
MetropoliceSubtitle_Map.StabilizationJurisDiction=稳定管辖区
MetropoliceSubtitle_Map.OutlandZone=周边区

MetropoliceSubtitle_Map.ResidentialBlock=住宅区
MetropoliceSubtitle_Map.404Zone=404 区
MetropoliceSubtitle_Map.DistributionBlock=配给区
MetropoliceSubtitle_Map.ProductionBlock=生产区

MetropoliceSubtitle_Map.HighPriorityRegion=高级权限区
MetropoliceSubtitle_Map.TerminalRestrictionZone=高级限制区
MetropoliceSubtitle_Map.ControlSection=政策控制区

# Crimes
MetropoliceSubtitle_Crime.CriminalTrespass63=63 非法侵入
MetropoliceSubtitle_Crime.NonSanctionedArson51=51 蓄意纵火
MetropoliceSubtitle_Crime.Posession69=69 资源占有
MetropoliceSubtitle_Crime.PublicNonCompliance507=507 妨害公共利益
MetropoliceSubtitle_Crime.RecklessOperation99=99 无畏战斗
MetropoliceSubtitle_Crime.ResistingPacification148=148 拒捕行为
MetropoliceSubtitle_Crime.Riot404=404 暴动
MetropoliceSubtitle_Crime.Fugitive17F=17-F 逮捕逃犯
MetropoliceSubtitle_Crime.Weapon94=94 武器
MetropoliceSubtitle_Crime.Alarms62=62 警报
MetropoliceSubtitle_Crime.Assault243=243 护卫队遭到攻击
MetropoliceSubtitle_Crime.IllegalCarrying95=95 非法携带枪支
MetropoliceSubtitle_Crime.UnlawfulEntry603=603 非法侵占

# Suspect Names
MetropoliceSubtitle_Suspect.Subject=目标
MetropoliceSubtitle_Suspect.Citizen=市民
MetropoliceSubtitle_Suspect.UPI=UPI
MetropoliceSubtitle_Suspect.NonCitizen=非市民
MetropoliceSubtitle_Suspect.Sociocide=反社会
MetropoliceSubtitle_Suspect.Anticitizen=反叛者
MetropoliceSubtitle_Suspect.Freeman=弗里曼
MetropoliceSubtitle_Suspect.Infection=感染
