
# EN-US
# Names
CombineSoldierSubtitle_Name.Leader=Leader
CombineSoldierSubtitle_Name.Flash=Flash
CombineSoldierSubtitle_Name.Ranger=Ranger
CombineSoldierSubtitle_Name.Hunter=Hunter
CombineSoldierSubtitle_Name.Blade=Blade
CombineSoldierSubtitle_Name.Scar=Scar
CombineSoldierSubtitle_Name.Hammer=Hammer
CombineSoldierSubtitle_Name.Sweeper=Sweeper
CombineSoldierSubtitle_Name.Swift=Swift
CombineSoldierSubtitle_Name.Fist=Fist
CombineSoldierSubtitle_Name.Sword=Sword
CombineSoldierSubtitle_Name.Savage=Savage
CombineSoldierSubtitle_Name.Slash=Slash
CombineSoldierSubtitle_Name.Razor=Razor
CombineSoldierSubtitle_Name.Stab=Stab
CombineSoldierSubtitle_Name.Spear=Spear
CombineSoldierSubtitle_Name.Striker=Striker
CombineSoldierSubtitle_Name.Dagger=Dagger

CombineSoldierSubtitle_Name.Ghost=Ghost
CombineSoldierSubtitle_Name.Reaper=Reaper
CombineSoldierSubtitle_Name.Nomad=Nomad
CombineSoldierSubtitle_Name.Hurricane=Hurricane
CombineSoldierSubtitle_Name.Phantom=Phantom
CombineSoldierSubtitle_Name.Judge=Judge
CombineSoldierSubtitle_Name.Shadow=Shadow
CombineSoldierSubtitle_Name.Slam=Slam
CombineSoldierSubtitle_Name.Stinger=Stinger
CombineSoldierSubtitle_Name.Storm=Storm
CombineSoldierSubtitle_Name.Vamp=Vamp
CombineSoldierSubtitle_Name.Winder=Winder
CombineSoldierSubtitle_Name.Star=Star

CombineSoldierSubtitle_Target.Freeman3=Freeman
CombineSoldierSubtitle_Target.AntiCitizenOne=Anti-citizen One
CombineSoldierSubtitle_Target.TargetOne=Target One
CombineSoldierSubtitle_Target.Priority1Objective=Priority 1 Objective
CombineSoldierSubtitle_Target.Ghost2=Ghost 2

CombineSoldierSubtitle_Code.Apex=Apex
CombineSoldierSubtitle_Code.Ion=Ion
CombineSoldierSubtitle_Code.Jet=Jet
CombineSoldierSubtitle_Code.Kilo=Kilo
CombineSoldierSubtitle_Code.Mace=Mace
CombineSoldierSubtitle_Code.Nova=Nova
CombineSoldierSubtitle_Code.Payback=Payback
CombineSoldierSubtitle_Code.Sundown=Sundown
CombineSoldierSubtitle_Code.Uniform=Uniform
CombineSoldierSubtitle_Code.Boomer=Boomer
CombineSoldierSubtitle_Code.Echo=Echo
CombineSoldierSubtitle_Code.Flatline=Flatline
CombineSoldierSubtitle_Code.Helix=Helix
CombineSoldierSubtitle_Code.Ice=Ice
CombineSoldierSubtitle_Code.Quicksand=Quicksand
CombineSoldierSubtitle_Code.Ripcord=Ripcord
