
# EN-US
# Names
CombineSoldierSubtitle_Name.Leader=Leader
CombineSoldierSubtitle_Name.Flash=Flash
CombineSoldierSubtitle_Name.Ranger=Ranger
CombineSoldierSubtitle_Name.Hunter=Hunter
CombineSoldierSubtitle_Name.Blade=Blade
CombineSoldierSubtitle_Name.Scar=Scar
CombineSoldierSubtitle_Name.Hammer=Hammer
CombineSoldierSubtitle_Name.Sweeper=Sweeper
CombineSoldierSubtitle_Name.Swift=Swift
CombineSoldierSubtitle_Name.Fist=Fist
CombineSoldierSubtitle_Name.Sword=Sword
CombineSoldierSubtitle_Name.Savage=Savage
CombineSoldierSubtitle_Name.Slash=Slash
CombineSoldierSubtitle_Name.Razor=Razor
CombineSoldierSubtitle_Name.Stab=Stab
CombineSoldierSubtitle_Name.Spear=Spear
CombineSoldierSubtitle_Name.Striker=Striker
CombineSoldierSubtitle_Name.Dagger=Dagger

CombineSoldierSubtitle_Name.Ghost=Ghost
CombineSoldierSubtitle_Name.Reaper=Reaper
CombineSoldierSubtitle_Name.Nomad=Nomad
CombineSoldierSubtitle_Name.Hurricane=Hurricane
CombineSoldierSubtitle_Name.Phantom=Phantom
CombineSoldierSubtitle_Name.Judge=Judge
CombineSoldierSubtitle_Name.Shadow=Shadow
CombineSoldierSubtitle_Name.Slam=Slam
CombineSoldierSubtitle_Name.Stinger=Stinger
CombineSoldierSubtitle_Name.Storm=Storm
CombineSoldierSubtitle_Name.Vamp=Vamp
CombineSoldierSubtitle_Name.Winder=Winder
CombineSoldierSubtitle_Name.Star=Star

CombineSoldierSubtitle_Name.Freeman3=Freeman
CombineSoldierSubtitle_Name.AntiCitizenOne=Anti-citizen One
CombineSoldierSubtitle_Name.TargetOne=Target One
CombineSoldierSubtitle_Name.Priority1Objective=Priority 1 Objective
CombineSoldierSubtitle_Name.Ghost2=Ghost 2

CombineSoldierSubtitle_Name.Apex=Apex
CombineSoldierSubtitle_Name.Ion=Ion
CombineSoldierSubtitle_Name.Jet=Jet
CombineSoldierSubtitle_Name.Kilo=Kilo
CombineSoldierSubtitle_Name.Mace=Mace
CombineSoldierSubtitle_Name.Nova=Nova
CombineSoldierSubtitle_Name.Payback=Payback
CombineSoldierSubtitle_Name.Sundown=Sundown
CombineSoldierSubtitle_Name.Uniform=Uniform
CombineSoldierSubtitle_Name.Boomer=Boomer
CombineSoldierSubtitle_Name.Echo=Echo
CombineSoldierSubtitle_Name.Flatline=Flatline
CombineSoldierSubtitle_Name.Helix=Helix
CombineSoldierSubtitle_Name.Ice=Ice
CombineSoldierSubtitle_Name.Quicksand=Quicksand
CombineSoldierSubtitle_Name.Ripcord=Ripcord
