
# EN-US
# Names
MetropoliceSubtitle_Name.Defender=Defender
MetropoliceSubtitle_Name.Hero=Hero
MetropoliceSubtitle_Name.Jury=Jury
MetropoliceSubtitle_Name.King=King
MetropoliceSubtitle_Name.Line=Line
MetropoliceSubtitle_Name.Patrol=Patrol
MetropoliceSubtitle_Name.Quick=Quick
MetropoliceSubtitle_Name.Roller=Roller
MetropoliceSubtitle_Name.Stick=Stick
MetropoliceSubtitle_Name.Tap=Tap
MetropoliceSubtitle_Name.Union=Union
MetropoliceSubtitle_Name.Victor=Victor
MetropoliceSubtitle_Name.Xray=Xray
MetropoliceSubtitle_Name.Yellow=Yellow
MetropoliceSubtitle_Name.Vice=Vice

# Maps
MetropoliceSubtitle_Map.Block=Block
MetropoliceSubtitle_Map.Zone=Zone
MetropoliceSubtitle_Map.Sector=Sector

MetropoliceSubtitle_Map.StationBlock=Station Block
MetropoliceSubtitle_Map.TransitBlock=Transit Block
MetropoliceSubtitle_Map.WorkforceIntake=Workforce Intake

MetropoliceSubtitle_Map.CanalBlock=Canal Block
MetropoliceSubtitle_Map.StormSystem=Storm System
MetropoliceSubtitle_Map.WasteRiver=Waste River
MetropoliceSubtitle_Map.DeservicedArea=Deserviced Area

MetropoliceSubtitle_Map.IndustrialZone=Industrial Zone
MetropoliceSubtitle_Map.RestrictedBlock=Restricted Block
MetropoliceSubtitle_Map.RepurposedArea=Repurposed Area

MetropoliceSubtitle_Map.CondemnedZone=Condemned Zone
MetropoliceSubtitle_Map.InfestedZone=Infested Zone
MetropoliceSubtitle_Map.NonPatrolRegion=Non-Patrol Region

MetropoliceSubtitle_Map.ExternalJurisDiction=External Juris Diction
MetropoliceSubtitle_Map.StabilizationJurisDiction=Stabilization Juris Diction
MetropoliceSubtitle_Map.OutlandZone=Outland Zone

MetropoliceSubtitle_Map.ResidentialBlock=Residential Block
MetropoliceSubtitle_Map.404Zone=404 Zone
MetropoliceSubtitle_Map.DistributionBlock=Distribution Block
MetropoliceSubtitle_Map.ProductionBlock=Production Block

MetropoliceSubtitle_Map.HighPriorityRegion=High Priority Region
MetropoliceSubtitle_Map.TerminalRestrictionZone=Terminal Restriction Zone
MetropoliceSubtitle_Map.ControlSection=Control Section

# Crimes
MetropoliceSubtitle_Crime.CriminalTrespass63=63 Criminal Trespass
MetropoliceSubtitle_Crime.NonSanctionedArson51=51 Non-Sanctioned Arsonment
MetropoliceSubtitle_Crime.Posession69=69 Posession Resources
MetropoliceSubtitle_Crime.PublicNonCompliance507=507 Public Non-Compliance
MetropoliceSubtitle_Crime.RecklessOperation99=99 Reckless Operation
MetropoliceSubtitle_Crime.ResistingPacification148=148 Resisting Arrest
MetropoliceSubtitle_Crime.Riot404=404 Riot
MetropoliceSubtitle_Crime.Fugitive17F=17-F Fugitive Detachment
MetropoliceSubtitle_Crime.Weapon94=94 Weapon
MetropoliceSubtitle_Crime.Alarms62=62 Alarms
MetropoliceSubtitle_Crime.Assault243=243 Assault on Protection Team
MetropoliceSubtitle_Crime.IllegalCarrying95=95 Illegal Carrying
MetropoliceSubtitle_Crime.UnlawfulEntry603=603 Unlawful Entry

# Suspect Names
MetropoliceSubtitle_Suspect.Subject=Subject
MetropoliceSubtitle_Suspect.Citizen=Citizen
MetropoliceSubtitle_Suspect.UPI=UPI
MetropoliceSubtitle_Suspect.NonCitizen=Non-Citizen
MetropoliceSubtitle_Suspect.Sociocide=Socio-cide
MetropoliceSubtitle_Suspect.Anticitizen=Anticitizen
MetropoliceSubtitle_Suspect.Freeman=Freeman
MetropoliceSubtitle_Suspect.Infection=Infection

# Punishments
MetropoliceSubtitle_Punish.PermanentOffWorld=Permanent Off-World service assignment
MetropoliceSubtitle_Punish.ImmediateAmputation=Immediate Amputation
MetropoliceSubtitle_Punish.HalfReproductionCredits=50 Percent Reproduction Credits
MetropoliceSubtitle_Punish.HalfRankPoints=50 Percent Rank Points